name: env_pyevalai_server
channels:
  - anaconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - certifi=2024.12.14=py313h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cloudpickle=3.0.0=py313h06a4308_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipython=8.30.0=py313h06a4308_0
  - jedi=0.19.2=py313h06a4308_0
  - jinja2=3.1.5=py313h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - ldap3=2.9.1=pyhd3eb1b0_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - markdown2=2.4.0=pyhd3eb1b0_0
  - markupsafe=2.1.3=py313h5eee18b_1
  - matplotlib-inline=0.1.6=py313h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - natsort=7.1.1=pyhd3eb1b0_0
  - ncurses=6.4=h6a678d5_0
  - numpy=2.2.2=py313hf4aebb8_0
  - numpy-base=2.2.2=py313h3fc9231_0
  - openssl=3.0.15=h5eee18b_0
  - parso=0.8.4=py313h06a4308_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=24.2=py313h06a4308_0
  - prompt-toolkit=3.0.43=py313h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.6.1=py313h06a4308_0
  - pygments=2.15.1=py313h06a4308_1
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.1=hf623796_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py313h06a4308_1
  - setuptools=72.1.0=py313h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py313h5eee18b_0
  - traitlets=5.14.3=py313h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py313h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.44.0=py313h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - filelock==3.13.1
      - fsspec==2024.6.1
      - mpmath==1.3.0
      - networkx==3.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - pillow==11.0.0
      - sympy==1.13.1
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - triton==3.2.0
      - typing-extensions==4.12.2
prefix: /home/wandel/anaconda3/envs/env_server
